### ISSUE TITLE
Day 1 Free Writing: "Writing1QualityCheck" not working

### ISSUE THREAD

**Issue by Pablo-Yin** [Harrilee/CPT-BE-2024#16]
1. Variable "Writing1QualityCheck" didn't automatically change when "Writing1QualityCheckRA" and "Writing1QualityCheckCS" were set.
2. Will "Writing1QualityCheckNotified" be automatically checked if notification is sent to users via Blued?
<img width="1174" alt="image" src="https://github.com/user-attachments/assets/4d900c27-a224-46cc-aea5-52318190a1d6">

**Comment by Pablo-Yin** [comment]
@YongyuLiu03 @Harrilee

**Comment by Pablo-Yin** [comment]
> “2. Will Writing1QualityCheckNotified be automatically checked if notification is sent to users via Blued?”

Blued notification didn't work when _Writing1QualityCheckNotified_ was "False". @YongyuLiu03 
<img width="1174" alt="image" src="https://github.com/user-attachments/assets/e8aafe21-2803-42a7-b3fe-45d69aa053e6">

**Comment by YongyuLiu03** [comment]
> > “2. Will Writing1QualityCheckNotified be automatically checked if notification is sent to users via Blued?”
> 
> Blued notification didn't work when _Writing1QualityCheckNotified_ was "False". @YongyuLiu03 <img alt="image" width="1174" src="https://private-user-images.githubusercontent.com/168945753/362294042-e8aafe21-2803-42a7-b3fe-45d69aa053e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Nzg0MTUsIm5iZiI6MTcyNDg3ODExNSwicGF0aCI6Ii8xNjg5NDU3NTMvMzYyMjk0MDQyLWU4YWFmZTIxLTI4MDMtNDJhNy1iM2ZlLTQ1ZDY5YWEwNTNlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQyMDQ4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjNiNDhhMTliYWM3MjU5MGI1YWQ5NzMxZGJiMmQ0ODFmM2RlMWJkMzBlMzhjZjVlOTNlMzRhNTU3YThmYzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SfHHd-OI1iAX5UayMLLelQUExhpoGg8QLR48bdyhqZY">

It's because when day 1 quality check fails, user is banned and system will send banned notification in prior, and writing quality low notification is skipped.  (Banned notification also explains the banned reason which is low writing quality)

**Comment by Pablo-Yin** [comment]
But I didn't seem to receive the banned notification at 8 p.m. on Day 1. Also, I didn't get a reminder that the tasks have started at 8 a.m. on Day 2 after I changed my quality check status to TRUE yesterday at night.
