### ISSUE TITLE
Notification Not Working

### ISSUE THREAD

**Issue by Pablo-Yin** [Harrilee/CPT-BE-2024#21]
Day 3 任务开启提醒 8 a.m. not working. @YongyuLiu03

**Comment by Harrilee** [comment]
Should have worked now. Please let me know when you receive the next notification. @Pablo-Yin

**Comment by Pablo-Yin** [comment]
> Should have worked now. Please let me know when you receive the next notification. @Pablo-Yin

Still couldn't receive a reminder at 8 p.m. the day before the intervention began.

**Comment by Harrilee** [comment]
Hi @YongyuLiu03 ,
I did see the logs indicating that the event has been successfully triggered. Could you have a look on what's going on here? Thanks!

<img width="623" alt="image" src="https://github.com/user-attachments/assets/17906b80-d746-45e8-9f63-647725fd5673">

**Comment by YongyuLiu03** [comment]
@Harrilee @Pablo-Yin Should now be resolved. Please log in to the website to receive future notifications. Also, please help me observe the triggered times, as I am still testing the timezone settings.

**Comment by Pablo-Yin** [comment]
> @Harrilee @Pablo-Yin Should now be resolved. Please log in to the website to receive future notifications. Also, please help me observe the triggered times, as I am still testing the timezone settings.

There seems to be some problems with the triggered time. I didn't complete the tasks on Day 1, but I received no reminders. @YongyuLiu03
